catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'packages/*'

catalogs:

  doc:
    '@shikijs/markdown-it': ^3.2.1
    '@types/markdown-it-link-attributes': ^3.0.5
    markdown-it-link-attributes: ^4.0.1
    shiki: ^3.2.1
    vitepress: 2.0.0-alpha.15

  playground:
    "@types/node": "^24.10.1"
    "@vitejs/plugin-vue": "^6.0.1"
    "@vue/tsconfig": "^0.8.1"
    "typescript": "~5.9.3"
    "vite": "npm:rolldown-vite@7.2.5"
    "vue-tsc": "^3.1.4"
    "vue": "^3.5.24"

  utils:
    '@antfu/eslint-config': ^4.11.0
    '@iconify-json/carbon': ^1.2.8
    '@intlify/unplugin-vue-i18n': ^6.0.5
    '@types/file-saver': ^2.0.7
    '@types/node': ^25.0.2
    '@unocss/eslint-config': ^66.1.0-beta.7
    '@vitejs/plugin-vue': ^5.2.3
    '@vitest/ui': ^3.0.9
    '@vue-macros/volar': ^3.0.0-beta.7
    '@vue/test-utils': ^2.4.6
    decimal.js: ^10.6.0
    eslint: ^9.23.0
    eslint-plugin-cypress: ^4.2.0
    eslint-plugin-format: ^1.0.1
    exceljs: ^4.4.0
    file-saver: ^2.0.5
    typescript: ^5.8.2
    vite-plugin-dts: ^4.5.4
    vitest: ^3.0.9
    vite: ^7.0.0
    vue-tsc: ^2.2.8
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
